### PR TITLE
Replacing regular Abuse map with Toxic Abuse map

### PR DESCRIPTION
**Pull request by acerspyro**
Per @shacknetisp 's suggestion, I am proposing to replace the regular Abuse map with my Toxic Abuse remix. You can grab the .zip to test it from here: https://redeclipse.net/forum/viewtopic.php?f=5&t=1208&p=10722

This is Toxic Abuse's lore:

> Back in its golden days, the toxic waste processing facility would process up to 500 000 tons of toxic, carcinogenic, or otherwise harmful biochemicals every day.

>The plant rid a multitude of labs and factories all around the globe (well, what's left of it anyway) of all forms of dangerous factory by-products, such as narcotics, acids as well as defective biochemical weaponry, which were commonly dumped in facilities just like this one.

>The company owning the plant, Owens Waste Processing Co., went out of business five years before the great war of 3078.
>The war having decimated 65% of the world's population, there was nobody left to keep the plant and its toxic waste in control.

>Over the years, without a working drainage system, the waste levels rose to the point where only the top two floors are left intact.

>Your goal, as a team or on your own, is to win custody of the plant in order for you to set camp there to ready up for the upcoming biological warfare.

Here are some screenshots for the lazy:

### CODE REVIEW

**Comment by TheAssassin** [comment]
I would've renamed the files as well. 

@molexted, please add the old abuse files to your PR.

**Comment by shacknetisp** [comment]
This is still abuse, just with a big facelift, similar to the echo1k -> echo2k change. Seeing as we're getting rid of the old abuse I don't see why we'd need to make the change any slightly more difficult.

**Comment by TheAssassin** [comment]
The map is pretty much different, like a new version. I would've liked to see that reflected in the map's name. If anyone wants to host abuse in parallel, they'd have to rename the "old" one now, although everyone's used to the "old" one as the default.

**Comment by acerspyro** [comment]
echo2k's map name is still "echo" though.

**Comment by qreeves** [comment]
Legacy support is not our concern, it is the name of an official map that received an update (like any other update). The names should stay the same.

**Pull request merged**
