### PR TITLE
Big update to map Bath

### PR DESCRIPTION
**Pull request by acerspyro**
# **WARNING: Please merge https://github.com/red-eclipse/acerspyro/pull/1 before merging this map**

I brought a ton of updades to Bath. Environment updates, texture updates, lighting updates, geometry updates, new and removed elements, you name it.

A ton of texture glitches have been fixed
Geometry has been simplified and improved
The ground water has been removed as this was a common cause of low performance on this map
I replaced all the light textures with my own, higher-res version (see warning)
The items have a little platform on which to spawn

Listing all the little changes I made would be way too long, so here are some screenshots:

### CODE REVIEW

**Comment by acerspyro** [comment]
I got some complaints about the weaponspawns not fitting in with the rest of the map. Here are some ideas, help me pick one or suggest something.

**Comment by shacknetisp** [comment]
I think the pads should be removed entirely or at least be severely dimmed, weapons already glow and it'd look silly to have the glowing pads there outside of classic mode.

**Comment by acerspyro** [comment]
I settled on this design. Unless you require something from me, I am done with this map. Don't forget to merge my textures first.

**Comment by qreeves** [comment]
If you use the palette system for the pads then weapons that aren't available aren't coloured (which is what the map was previously using as it was my demo map for the palette system).

**Comment by acerspyro** [comment]
@qreeves I do not think the palette system works with vshaderparam glowscale

**Comment by qreeves** [comment]
Sure it does, you can colour the whole texture with the regular `vpalette`, or you can specify it specifically for the glow colour with `vshaderparam glowcolor <r> <g> <b> 1 <palette> <index>`

**Pull request merged**
